"""Run-level traceability helpers for the RICO pipeline.

Provides:
- Pipeline run lifecycle (create / update rows in pipeline_runs).
- SHA-256 fingerprinting for source-byte traceability.
- Git SHA capture for code-version traceability.
"""

import hashlib
import logging
import subprocess
from datetime import datetime, timezone
from uuid import UUID

import psycopg

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Pipeline run lifecycle
# ---------------------------------------------------------------------------

def create_pipeline_run(
    conn: psycopg.Connection,
    dag_run_id: str,
    limit_param: int,
    *,
    clip_version: str = "ViT-B-32",
    sbert_version: str = "all-MiniLM-L6-v2",
    llm_version: str = "qwen2.5:3b",
    prompt_version: str = "v1",
) -> UUID:
    """Insert a new row into pipeline_runs and return its run_id.

    The run_id is auto-generated by Postgres (DEFAULT gen_random_uuid()).
    The row is created with status='running' and started_at=now().

    Args:
        conn: An open psycopg connection (will be committed by caller).
        dag_run_id: Airflow's DAG run identifier string.
        limit_param: Number of screens this run will process.
        clip_version: CLIP model version string.
        sbert_version: SBERT model version string.
        llm_version: Ollama model identifier.
        prompt_version: Extraction prompt version tag.

    Returns:
        The UUID assigned to this pipeline run.
    """
    sql = """
        INSERT INTO pipeline_runs
            (dag_run_id, started_at, status, limit_param,
             git_sha, clip_version, sbert_version, llm_version, prompt_version)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING run_id
    """
    now = datetime.now(timezone.utc)
    git_sha = get_git_sha()

    with conn.cursor() as cur:
        cur.execute(sql, (
            dag_run_id,
            now,
            "running",
            limit_param,
            git_sha,
            clip_version,
            sbert_version,
            llm_version,
            prompt_version,
        ))
        run_id = cur.fetchone()[0]
    conn.commit()

    log.info("[run_id=%s] Pipeline run created (dag_run_id=%s, limit=%d)",
             run_id, dag_run_id, limit_param)
    return run_id


def update_pipeline_run(
    conn: psycopg.Connection,
    run_id: UUID,
    status: str,
    ended_at: datetime | None = None,
) -> None:
    """Update an existing pipeline_runs row with final status and end time.

    Args:
        conn: An open psycopg connection (will be committed by caller).
        run_id: The UUID of the run to update.
        status: Final status string (e.g. 'success', 'failed', 'audit_failed').
        ended_at: Completion timestamp. Defaults to now(UTC) if not provided.
    """
    if ended_at is None:
        ended_at = datetime.now(timezone.utc)

    sql = """
        UPDATE pipeline_runs
           SET status = %s, ended_at = %s
         WHERE run_id = %s
    """
    with conn.cursor() as cur:
        cur.execute(sql, (status, ended_at, run_id))
    conn.commit()

    log.info("[run_id=%s] Pipeline run updated: status=%s", run_id, status)


# ---------------------------------------------------------------------------
# Source fingerprinting
# ---------------------------------------------------------------------------

def sha256_fingerprint(data: bytes) -> str:
    """Return the SHA-256 hex digest of the given bytes.

    Used to produce a source_fingerprint for every row in destination tables.
    For images: pass the raw PNG bytes. For text: pass the UTF-8 encoded string.

    Args:
        data: Raw bytes to hash.

    Returns:
        64-character lowercase hex string.
    """
    return hashlib.sha256(data).hexdigest()


# ---------------------------------------------------------------------------
# Git SHA capture
# ---------------------------------------------------------------------------

def get_git_sha() -> str:
    """Return the current git commit SHA (short form), or 'unknown'.

    Runs ``git rev-parse --short HEAD`` in a subprocess. If git is not
    available or the working directory is not a repo, returns 'unknown'
    without raising.

    Returns:
        7-character git SHA string, or 'unknown'.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"
